labels:
  app: istio-ingressgateway
annotations: {}
image: to-be-injected-by-imagevector
trustDomain: cluster.local
istiodNamespace: istio-system
deployNamespace: false
serviceType: LoadBalancer
ports: []
# ports:
# - name: tls
#   port: 443
#   targetPort: 443
#
#- name: tcp
#  port: 8443
#  targetPort: 8443
